stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo ${SECRET_DOCKER} > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
      

