stages:
  - test
  - deploy
  

test:
  stage: test
  image: node:alpine
  services:
    - name: aucante/nodejs-alpine:latest
      alias: nodejs-app
  variables:
    API_HOST: nodejs-app
  script:
    - npm install jest
    - npx jest

deploy:
  stage: deploy
  image: alpine
  script:
    - apk add aws-cli curl make
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - make update-kube-config
    - ./kubectl apply -f k8s/deployment.yaml
