stages:
  - build
  - test

build:
  stage: build
  script:
    - make build

test:
  stage: test
  script:
    - make build-and-run-tests

build-docker-image:
  image: gitlab/dind
  services:
    - docker:dind
  stage: build-docker-image
  script:
    - docker info
