stages:
  - build
  - test

build:
  stage: build
  script:
    - apt update && apt install make -y
    - make build

test:
  stage: test
  script:
    - apt update && apt install make -y
    - make build-and-run-tests
