stages:
  - build
  - test
  - build-docker-image

build:
  stage: build
  script:
    - make build

test:
  stage: test
  script:
    - make build-and-run-tests

build-docker-image:
  image: docker:stable
  services:
    - docker:dind
  stage: build-docker-image
  script:
    - docker info
