stages:
  - build
  - test

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo $SECRET_DOCKER > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "aucante/nodejs-alpine:latest"

test:
  stage: test
  image: node:alpine
  services:
    - name: aucante/nodejs-alpine:latest
      alias: nodejs-app
  variables:
    API_HOST: nodejs-app
  script:
    - npm install jest
    - npx jest
