stages:
  - build
  - test

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo $SECRET_DOCKER > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "aucante/nodejs-alpine:latest"
  only:
    changes:
      - Dockerfile
      
test:
  stage: build
  image: alpine
  services:
    - name: aucante/nodejs-alpine:latest
      alias: service-nodejs-app  
  script:
    - apk add curl
    - curl http://service-nodejs-app:3000