stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - make build

test:
  stage: test
  script:
    - make build-and-run-tests

deploy:
  stage: deploy
  script:
    - make stop
