stages:
  - build
  - test

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo $SECRET_DOCKER > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "aucante/nodejs-alpine:latest"
  only:
    changes:
      - Dockerfile
      
test:
  stage: test
  image:
    name: ubuntu:22.10
    entrypoint: [""]
  script:
    - docker run --privileged docker:stable-dind
    - docker pull aucante/nodejs-alpine:latest
    - docker run --name nodejs-alpine-container -d aucante/nodejs-alpine:latest
    - docker exec -it nodejs-alpine-container npx jest
